### ISSUE TITLE
`DOMParser.parseFromString` requires 2 arguments

### ISSUE THREAD

**Issue by diomidov** [edemaine/svgtiler#37]
https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

The second argument is optional in the `xmldom` implementation but it is required when running in the browser.

**Comment by edemaine** [comment]
@diomidov Thanks! This is a helpful step in the direction of getting things to run in-browser, which perhaps we should open as a general issue, depending on how many things you find.

Do you want an immediate release with this fix, or are you OK working from master?

Are you using webpack or something else to browserify svgtiler? I imagine it should also export a lot of stuff like the classes?

**Comment by diomidov** [comment]
I'll probably fork svgtiler and add it as a submodule to my repo.

I'm currently using browserify, although I'm also looking into webpack.

**Comment by edemaine** [comment]
Yeah, submodules would work, though I've found them a pain to work with.  Alternatively, in the GUI repo, you `npm install` your fork via the github repo URL.  It'd be great to get a PR for the svgtiler repo so that we don't need two versions long-term. 

Plausibly the GUI could be part of the same repo, too (mono-repo style). Alternatively, maybe I should make an svgtiler organization that has the current svgtiler repo and an svgtiler-gui repo? Anyway, we can decide this later.
